name: github pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  
          fetch-depth: 0    
      
      - name: set up WARP
        uses: fscarmen/warp-on-actions@v1.0
        with:
          mode: wireguard
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          #force_orphan: true
          #commit_message: ${{ github.event.head_commit.message }}